FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=yourStrongPassword123
ENV WEBHOOK_URL=https://karmakosha.onrender.com
ENV N8N_PORT=5678
ENV N8N_HOST=0.0.0.0

EXPOSE 5678
